// Dicionário inglês: chave = texto original em português (com {marcadores}), valor = tradução.
// Texto sem entrada aparece em português. Textos do mapa e o narrador ficam em japonês nos dois idiomas.
export const EN = {
  // --- Menu inicial e telas ---------------------------------------------------------------------------------
  '湾岸ドリフト · DRIFT NOTURNO': '湾岸ドリフト · NIGHT DRIFT',
  'SINGLEPLAYER': 'SINGLEPLAYER',
  'Corrida contra a IA ou treino livre, recordes locais': 'Race the AI or practice freely, local records',
  'PERFIL': 'PROFILE',
  'Estatísticas de piloto, medalhas e itens liberados': 'Driver stats, medals and unlocked items',
  'MULTIPLAYER': 'MULTIPLAYER',
  'EM BREVE': 'COMING SOON',
  'Correr com outros jogadores online': 'Race other players online',
  'CONFIGURAÇÕES': 'SETTINGS',
  'Volumes, vídeo, câmera, interface e controles': 'Volume, video, camera, interface and controls',
  'PISTA': 'TRACK',
  'HORÁRIO': 'TIME',
  'CARRO': 'CAR', 'CARROS': 'CARS', 'PREPARAÇÃO': 'TUNING', 'PEÇAS': 'PARTS',
  'CAIXA ¥ {money}': 'CASH ¥ {money}', 'NA PISTA': 'ON TRACK', 'NA GARAGEM': 'OWNED', 'COMPRADO': 'BOUGHT', 'MÁX.': 'MAX',
  'Já está na sua garagem. Enter coloca na pista.': 'Already in your garage. Enter puts it on track.',
  'Comprar por ¥ {price}.': 'Buy for ¥ {price}.', 'Estágio {n} de {max} em {car}.': 'Stage {n} of {max} on {car}.',
  'Preparação no máximo.': 'Fully tuned.', 'Próximo estágio: ¥ {price}': 'Next stage: ¥ {price}',
  'também sai com a medalha {name}': 'also unlocked by the {name} medal', 'exclusivo do BODYSHOP': 'BODYSHOP exclusive',
  'Liberado: escolha na GARAGEM de qualquer carro.': 'Unlocked: pick it in any car\'s GARAGE.',
  'Comprar por ¥ {price}. Vale para todos os carros.': 'Buy for ¥ {price}. Works on every car.',
  '{car} na pista.': '{car} on track.', 'Saldo insuficiente: faltam ¥ {money}.': 'Not enough cash: ¥ {money} short.',
  '{car} comprado! Já está na sua garagem.': '{car} bought! It\'s in your garage.', '{name} estágio {n} instalado.': '{name} stage {n} installed.',
  '{name} liberado na GARAGEM.': '{name} unlocked in the GARAGE.', 'medalha {name} ou BODYSHOP': '{name} medal or BODYSHOP',
  'à venda no BODYSHOP': 'for sale at the BODYSHOP',
  '{power} cv · {torque} N·m · {mass} kg · {ratio} kg/cv': '{power} hp · {torque} N·m · {mass} kg · {ratio} kg/hp',
  'PREPARAÇÃO DO MOTOR': 'ENGINE TUNING', 'REDUÇÃO DE PESO': 'WEIGHT REDUCTION', 'PNEUS': 'TYRES', 'SUSPENSÃO': 'SUSPENSION', 'FREIOS': 'BRAKES', 'KIT DE ÂNGULO': 'ANGLE KIT',
  'PINTURA': 'PAINT', 'RODAS': 'WHEELS', 'COR DA RODA': 'WHEEL COLOR', 'ADESIVO': 'STICKER', 'RASTRO DE DRIFT': 'DRIFT TRAIL',
  'Carros, preparação e peças: gaste os ¥ das corridas': 'Cars, tuning and parts: spend your race ¥', 'Peça arrancada': 'Part torn off', '{n} peças arrancadas': '{n} parts torn off', 'TAMANHO': 'SIZE', 'tamanho dos painéis na corrida': 'size of the in-race panels',
  '¥ {money}': '¥ {money}', 'lataria: conserto por ¥ {cost}': 'body: repair for ¥ {cost}',
  '¥ {money} · lataria sem avarias': '¥ {money} · body with no damage',
  'REPARAR ¥ {cost}': 'REPAIR ¥ {cost}', 'REPARAR LATARIA': 'REPAIR BODY',
  'PRÊMIO ¥ {prize}': 'PRIZE ¥ {prize}', 'caixa ¥ {money}': 'cash ¥ {money}', 'conserto ¥ {cost}': 'repair ¥ {cost}',
  'DINHEIRO': 'MONEY', 'GANHO NA CARREIRA': 'CAREER EARNINGS',
  'VOLTAS': 'LAPS',
  'GRID': 'GRID',
  'NÍVEL': 'LEVEL',
  'INICIAR CORRIDA': 'START RACE',
  'GARAGEM': 'GARAGE',
  'RANKING': 'RANKING',
  'VOLTAR': 'BACK',
  'FICHA TÉCNICA': 'SPECS',
  'PINTURA': 'PAINT',
  'RODAS': 'WHEELS',
  'COR RODA': 'RIM COLOR',
  'AEROFÓLIO': 'WING',
  'ALTURA': 'HEIGHT',
  'ADESIVO': 'STICKER',
  'RASTRO': 'TRAIL',
  'PRONTO': 'DONE',
  'RESTAURAR ORIGINAL': 'RESET TO STOCK',
  'Salvo por carro. O rastro de luz aparece quando o combo de drift está valendo.': 'Saved per car. The light trail shows while a drift combo is live.',
  'ランキング · 10 MELHORES VOLTAS': 'ランキング · TOP 10 LAPS',
  'Escolha contra qual fantasma correr: ele repete a volta gravada.': 'Pick which ghost to race: it replays the recorded lap.',
  'PERFIL DO PILOTO': 'DRIVER PROFILE',
  'CONTROLES': 'CONTROLS',
  'RESTAURAR PADRÕES': 'RESTORE DEFAULTS',
  'PAUSA': 'PAUSED',
  'CONTINUAR': 'RESUME',
  'REINICIAR CORRIDA': 'RESTART RACE',
  'MENU PRINCIPAL': 'MAIN MENU',
  'CHEGADA': 'FINISH',
  'CORRER DE NOVO': 'RACE AGAIN',
  'CARREGANDO': 'LOADING',
  'AO VIVO': 'LIVE',
  'Enter / A · PULAR': 'Enter / A · SKIP',
  'CÂMERA LIVRE': 'FREE CAMERA',
  '· WASD mover · arrastar o mouse olha · Espaço/E sobe · C/Q desce · Shift rápido · roda: velocidade · F ou Esc sai': '· WASD move · drag mouse to look · Space/E up · C/Q down · Shift fast · wheel: speed · F or Esc exits',
  'mais': 'more',
  'menos': 'less',

  // Setas dos seletores (acessibilidade)
  'PISTA: anterior': 'TRACK: previous', 'PISTA: próxima': 'TRACK: next', 'PISTA: próximo': 'TRACK: next',
  'HORÁRIO: anterior': 'TIME: previous', 'HORÁRIO: próximo': 'TIME: next',
  'CARRO: anterior': 'CAR: previous', 'CARRO: próxima': 'CAR: next', 'CARRO: próximo': 'CAR: next',
  'VOLTAS: anterior': 'LAPS: previous', 'VOLTAS: próxima': 'LAPS: next',
  'GRID: anterior': 'GRID: previous', 'GRID: próxima': 'GRID: next',
  'NÍVEL: anterior': 'LEVEL: previous', 'NÍVEL: próxima': 'LEVEL: next',
  'PINTURA: anterior': 'PAINT: previous', 'PINTURA: próximo': 'PAINT: next',
  'RODAS: anterior': 'WHEELS: previous', 'RODAS: próximo': 'WHEELS: next',
  'COR RODA: anterior': 'RIM COLOR: previous', 'COR RODA: próximo': 'RIM COLOR: next',
  'AEROFÓLIO: anterior': 'WING: previous', 'AEROFÓLIO: próximo': 'WING: next',
  'ALTURA: anterior': 'HEIGHT: previous', 'ALTURA: próximo': 'HEIGHT: next',
  'ADESIVO: anterior': 'STICKER: previous', 'ADESIVO: próximo': 'STICKER: next',
  'RASTRO: anterior': 'TRAIL: previous', 'RASTRO: próximo': 'TRAIL: next',

  // --- Singleplayer -----------------------------------------------------------------------------------------
  'TREINO LIVRE': 'FREE PRACTICE',
  '{n} VOLTAS': '{n} LAPS',
  '{n} VOLTA': '{n} LAP',
  'ALEATÓRIA': 'RANDOM',
  'ALEATÓRIO': 'RANDOM',
  'sorteada entre as {n} a cada largada': 'drawn from all {n} at every start',
  'sorteado a cada largada': 'drawn at every start',
  'sem chegada': 'no finish line',
  'corrida por pontos': 'points race',
  'SÓ VOCÊ': 'SOLO',
  '{n} CORREDORES': '{n} RACERS',
  'sem rivais': 'no rivals',
  'você + {n} rivais de IA': 'you + {n} AI rivals',
  'você + {n} rival de IA': 'you + {n} AI rival',
  'Pista e horário sorteados a cada largada entre: {list}.': 'Track and time drawn at every start from: {list}.',
  'Horário sorteado a cada largada ({list}).': 'Time of day drawn at every start ({list}).',
  'Treino livre: sem chegada, voltas contam para o recorde de volta.': 'Free practice: no finish, laps still count for the lap record.',
  'Pista aleatória: o recorde fica salvo na pista sorteada.': 'Random track: the record is saved on the track that was drawn.',
  'Recorde ({laps}): {points} pts': 'Record ({laps}): {points} pts',
  'Sem recorde nesta configuração ainda.': 'No record for this setup yet.',
  'LARGADA': 'START',
  'POTÊNCIA': 'POWER',
  'TORQUE': 'TORQUE',
  'PESO': 'WEIGHT',
  'PESO/POT.': 'PWR/WT',
  'TRAÇÃO': 'DRIVE',
  'TRASEIRA · {gears} MARCHAS · {front}% NA FRENTE': 'REAR · {gears} GEARS · {front}% FRONT',
  'MOTOR': 'ENGINE',
  'cv': 'hp',
  'medalha {name}': 'medal {name}',

  // Ranking
  'SEM FANTASMA': 'NO GHOST',
  'Nenhuma volta de {car} em {track} ainda. Complete uma volta pontuando para entrar no ranking.': 'No laps with {car} on {track} yet. Finish a scoring lap to get on the board.',
  'Fantasma: desligado': 'Ghost: off',
  'Fantasma: {pos}º do ranking · {points} pts': 'Ghost: #{pos} on the board · {points} pts',
  'Fantasma: nenhuma volta gravada com este carro': 'Ghost: no lap recorded with this car',

  // Pausa e resultado
  'volta de saída': 'out lap',
  'volta {lap} de {laps}': 'lap {lap} of {laps}',
  'volta {lap} (treino livre)': 'lap {lap} (free practice)',
  '{pos}º de {n}': '#{pos} of {n}',
  'POS': 'POS',
  'PILOTO': 'DRIVER',
  'PONTOS': 'POINTS',
  '(na pista)': '(still racing)',
  '{pos}º LUGAR': '#{pos} PLACE',
  'TOTAL': 'TOTAL',
  'NOVO RECORDE': 'NEW RECORD',
  'Recorde: {points} pts': 'Record: {points} pts',
  'VOLTA': 'LAP',
  'TEMPO': 'TIME',
  'TEMPO TOTAL': 'TOTAL TIME',
  'MAIOR COMBO': 'BEST COMBO',
  'VOLTA DE MAIS PONTOS': 'TOP-SCORING LAP',
  'RECORDE DA PISTA': 'TRACK RECORD',
  'RANKING DE VOLTAS': 'LAP RANKING',
  'MEDALHAS NOVAS': 'NEW MEDALS',
  'NOTAS DAS CURVAS': 'CORNER GRADES',

  // --- Perfil e medalhas ------------------------------------------------------------------------------------
  'KM RODADOS': 'KM DRIVEN',
  'AO VOLANTE': 'TIME DRIVING',
  'CORRIDAS': 'RACES',
  'de {n}': 'of {n}',
  'VITÓRIAS · PÓDIOS': 'WINS · PODIUMS',
  'PONTOS NA CARREIRA': 'CAREER POINTS',
  'MELHOR VOLTA': 'BEST LAP',
  'MELHOR CORRIDA': 'BEST RACE',
  'MAIOR ÂNGULO': 'MAX ANGLE',
  'DRIFT MAIS LONGO': 'LONGEST DRIFT',
  'BATIDAS NA MURETA': 'WALL HITS',
  'PISTA FAVORITA': 'FAVORITE TRACK',
  'CARRO FAVORITO': 'FAVORITE CAR',
  'MEDALHAS': 'MEDALS',
  '{score} pontos de medalha · próximo título: {name} com {at}': '{score} medal points · next title: {name} at {at}',
  '{score} pontos de medalha · título máximo': '{score} medal points · top title',
  'pilotando desde {date}': 'driving since {date}',
  'liberada em {date}': 'unlocked on {date}',
  'liberou {slot}: {item}': 'unlocked {slot}: {item}',
  'libera {slot}: {item}': 'unlocks {slot}: {item}',
  'libera {slot}': 'unlocks {slot}',
  'Medalha {medal}: {name}': '{medal} medal: {name}',
  'bronze': 'Bronze', 'prata': 'Silver', 'ouro': 'Gold',
  'pintura': 'paint', 'rodas': 'wheels', 'cor de roda': 'rim color', 'aerofólio': 'wing', 'altura': 'height', 'adesivo': 'sticker', 'rastro': 'trail',
  'feito': 'done', 'ainda não': 'not yet',
  '{n} curva': '{n} corner', '{n} curvas': '{n} corners',
  '{n} corrida': '{n} race', '{n} corridas': '{n} races',
  'Rodar': 'Drive',
  'Somar um combo de': 'Bank a combo of',
  'Segurar um drift a': 'Hold a drift at',
  'Manter um combo por': 'Keep one combo going for',
  'Tirar SS em': 'Score SS on',
  'Vencer (4+ corredores)': 'Win (4+ racers)',
  'PRIMEIROS QUILÔMETROS': 'FIRST KILOMETERS', 'ESTRADEIRO': 'ROAD WARRIOR', 'LENDA DA ESTRADA': 'ROAD LEGEND',
  'COMBO DE RESPEITO': 'RESPECTABLE COMBO', 'MÃO PESADA': 'HEAVY HAND', 'COMBO INFINITO': 'ENDLESS COMBO',
  'DE LADO': 'SIDEWAYS', 'QUASE DE RÉ': 'ALMOST BACKWARDS', 'ÂNGULO IMPOSSÍVEL': 'IMPOSSIBLE ANGLE',
  'DRIFT LONGO': 'LONG DRIFT', 'SEM SOLTAR': 'NEVER LET GO', 'MARATONA DE LADO': 'SIDEWAYS MARATHON',
  'NOTA MÁXIMA': 'TOP MARKS', 'COLECIONADOR DE SS': 'SS COLLECTOR', 'JUIZ ENCANTADO': 'JUDGES IN AWE',
  'PRIMEIRA VITÓRIA': 'FIRST WIN', 'TEMIDO NA SERRA': 'FEARED ON THE PASS', 'IMBATÍVEL': 'UNBEATABLE',
  'SEM ENCOSTAR': 'CLEAN RUN',
  'Terminar uma corrida de 3 voltas ou mais sem bater na mureta.': 'Finish a race of 3 or more laps without hitting a wall.',
  'REI DA CHUVA': 'RAIN KING',
  'Vencer no porto com chuva (4+ corredores).': 'Win at the port in the rain (4+ racers).',
  'REI DE HAKONE': 'KING OF HAKONE',
  'Vencer na Serra de Hakone contra 7 rivais, no Normal ou Simulação.': 'Win on the Hakone Pass against 7 rivals, on Normal or Simulation.',
  'TODOS OS CLIMAS': 'ALL WEATHER',
  'Terminar corridas em todas as {n} combinações de pista e horário.': 'Finish races in all {n} track and time combinations.',
  'NOVATO': 'ROOKIE', 'PILOTO DE RUA': 'STREET RACER', 'DRIFTER': 'DRIFTER', 'ÁS DO TOUGE': 'TOUGE ACE', 'LENDA': 'LEGEND',

  // --- Configurações ----------------------------------------------------------------------------------------
  'ÁUDIO': 'AUDIO', 'VÍDEO': 'VIDEO', 'JOGO': 'GAME', 'CORRIDA': 'RACE', 'INTERFACE': 'INTERFACE', 'IDIOMA': 'LANGUAGE', 'AMBIENTE': 'AMBIENCE', 'IDIOMA · LANGUAGE': 'LANGUAGE · IDIOMA', 'TEXTOS': 'TEXT',
  'GERAL': 'MASTER', 'MÚSICA': 'MUSIC', 'TRILHA': 'SOUNDTRACK', 'RIVAIS': 'RIVALS', 'EFEITOS': 'EFFECTS', 'NARRADOR': 'ANNOUNCER',
  'RESOLUÇÃO': 'RESOLUTION', 'EFEITO CRT': 'CRT EFFECT', 'NÉVOA': 'MIST', 'VISÃO': 'FIELD OF VIEW', 'FPS': 'FPS',
  'CÂMERA': 'CAMERA', 'CÂMBIO': 'GEARBOX', 'UNIDADE': 'UNITS', 'VIBRAÇÃO': 'RUMBLE', 'FANTASMA': 'GHOST', 'NOTAS': 'GRADES',
  'RASTRO DRIFT': 'DRIFT TRAIL', 'NOMES': 'NAMES', 'MINIMAPA': 'MINIMAP', 'SOBREVOO': 'FLYOVER',
  'MUDO': 'MUTE', 'LIGADO': 'ON', 'DESLIGADO': 'OFF', 'NATIVA': 'NATIVE', '{n} LINHAS': '{n} LINES',
  'padrão PS2 tardio': 'late PS2 default', 'mais nítido, mais pesado': 'sharpest, heaviest', 'mais leve e serrilhado': 'lighter and jaggier', 'mais nítido': 'sharper',
  'SUAVE': 'SUBTLE', 'NORMAL': 'NORMAL', 'FORTE': 'STRONG',
  'borrão de movimento dos quadros anteriores': 'motion blur from previous frames',
  'campo de visão da câmera': 'camera field of view',
  'TELA CHEIA': 'FULLSCREEN', 'Tela cheia': 'Fullscreen', 'Em janela': 'Windowed',
  'PERSEGUIÇÃO': 'CHASE', 'DISTANTE': 'FAR', 'CAPÔ': 'HOOD',
  'câmera ao largar (C troca na corrida)': 'starting camera (C switches while racing)',
  'AUTOMÁTICO': 'AUTOMATIC', 'MANUAL (Q/E)': 'MANUAL (Q/E)',
  'PORTUGUÊS': 'PORTUGUÊS', 'ENGLISH': 'ENGLISH',
  'textos do mapa e narrador em japonês': 'map signs and announcer stay in Japanese',
  'Narrador sem voz: o sistema não tem voz japonesa instalada. No Windows: Configurações › Hora e idioma › Fala › Adicionar vozes › Japonês.': 'Announcer is silent: no Japanese voice is installed. On Windows: Settings › Time & language › Speech › Add voices › Japanese.',

  // Controles
  'TECLADO': 'KEYBOARD', 'CONTROLE XBOX': 'XBOX CONTROLLER',
  'Acelerar': 'Throttle', 'Frear / ré (segure parado)': 'Brake / reverse (hold when stopped)', 'Esterçar': 'Steer',
  'Analógico esquerdo': 'Left stick', 'Freio de mão': 'Handbrake', 'Espaço': 'Space', 'ou': 'or',
  'Marchas (manual)': 'Gears (manual)', 'Câmera': 'Camera', 'Girar câmera 360°': 'Orbit camera 360°', 'arrastar o mouse': 'drag the mouse',
  'Analógico direito': 'Right stick', 'Voltar para a pista': 'Back on track', 'Pausar / voltar': 'Pause / back',
  'Assist. drift / TC / ABS': 'Drift assist / TC / ABS', 'Painel de debug / acerto': 'Debug / tuning panel',
  'Música liga/desliga · próxima': 'Music on/off · next', 'Câmera livre (voar pelo mapa)': 'Free camera (fly around the map)',
  'analógicos +': 'sticks +', 'Névoa / efeito CRT': 'Mist / CRT effect', 'Menus: navegar / escolher': 'Menus: navigate / select',
  'Dificuldade': 'Difficulty', 'Fantasma / câmbio / som': 'Ghost / gearbox / sound',
  'Com o controle ligado, clique nesta tela e aperte': 'With the controller on, click this screen and press',
  ': o navegador só mostra o controle depois de um botão apertado.': ': the browser only exposes a controller after a button press.',
  'Este navegador não tem suporte a controles (Gamepad API).': 'This browser does not support controllers (Gamepad API).',
  'Página fora de contexto seguro: abra por http://localhost.': 'Page is not in a secure context: open it via http://localhost.',
  'Nenhum controle visível para a página. Clique aqui na tela e aperte o botão A.': 'No controller visible to the page. Click here and press the A button.',
  'Controle Xbox': 'Xbox controller', 'Controle PlayStation': 'PlayStation controller', 'Controle': 'Controller',
  '{name} conectado': '{name} connected', '{name} desconectado': '{name} disconnected',
  'Nenhum controle: aperte A no controle com esta janela em foco': 'No controller: press A with this window focused',

  // --- HUD e corrida ----------------------------------------------------------------------------------------
  'SAÍDA': 'OUT LAP', 'PONTOS NA VOLTA': 'LAP POINTS', 'ÚLTIMA': 'LAST', 'MELHOR': 'BEST', 'POSIÇÃO': 'POSITION',
  'CLASSIFICAÇÃO': 'STANDINGS', 'ÂNGULO': 'ANGLE', 'LINHA': 'LINE', 'FUMAÇA': 'SMOKE', 'MARCHA': 'GEAR',
  'ACEL': 'THR', 'FREIO': 'BRK', 'DIR': 'STR', 'RÉ': 'REV', 'FÁCIL': 'EASY', 'SIMULAÇÃO': 'SIMULATION',
  'VOLTA {lap}/{laps}': 'LAP {lap}/{laps}', 'VOLTA {lap}': 'LAP {lap}', 'CURVA {n}': 'CORNER {n}', 'BATEU': 'CRASHED',
  'VOCÊ': 'YOU', 'JÁ!': 'GO!',
  'BATEU NA PAREDE': 'HIT THE WALL', 'BATEU NO CARRO': 'HIT A CAR', 'FORA DA RUA': 'OFF THE ROAD', 'RODOU': 'SPUN OUT',
  'TRANSIÇÃO': 'TRANSITION', 'ÂNGULO ALTO': 'HIGH ANGLE', 'RENTE À PAREDE': 'WALL HUGGER', 'NOTA {grade}': 'GRADE {grade}',
  'Volta no ranking: {rank}º lugar': 'Lap ranked #{rank}',
  'ÚLTIMA VOLTA': 'FINAL LAP',
  'Melhor volta: {points} pts': 'Best lap: {points} pts',
  'Volta: {points} pts': 'Lap: {points} pts',
  'Dica: {tip}': 'Tip: {tip}',
  'Dificuldade: {level}': 'Difficulty: {level}',
  'Acerto de debug carregado ({n} ajustes)': 'Debug tuning loaded ({n} changes)',
  'Acerto de debug carregado ({n} ajuste)': 'Debug tuning loaded ({n} change)',
  'Música ligada': 'Music on', 'Música desligada': 'Music off',
  'Câmera: {name}': 'Camera: {name}',
  'Perseguição': 'Chase', 'Perseguição distante': 'Far chase', 'Capô': 'Hood',
  'Câmbio automático': 'Automatic gearbox', 'Câmbio manual (Q / E)': 'Manual gearbox (Q / E)', 'Câmbio manual': 'Manual gearbox',
  'Som desligado': 'Sound off', 'Som ligado': 'Sound on',
  'Efeito CRT ligado': 'CRT effect on', 'Efeito CRT desligado': 'CRT effect off',
  'Névoa ligada': 'Mist on', 'Névoa desligada': 'Mist off',
  'Fantasma visível': 'Ghost visible', 'Fantasma oculto': 'Ghost hidden',
  'Controle de tração ligado (atrapalha o drift)': 'Traction control on (gets in the way of drifting)', 'Controle de tração desligado': 'Traction control off',
  'ABS ligado': 'ABS on', 'ABS desligado': 'ABS off',
  'Assistência de drift ligada': 'Drift assist on', 'Assistência de drift desligada': 'Drift assist off',
  'Carro personalizado carregado': 'Custom car loaded',
  'CÂMERA DA PISTA': 'TRACKSIDE CAM', 'HELICÓPTERO': 'HELICOPTER', 'LATERAL': 'SIDE', 'ÓRBITA': 'ORBIT', 'FRONTAL': 'FRONT',

  // Dicas da tela de carregamento
  'Trocar de lado sem perder o drift soma +0,5 no multiplicador.': 'Switching sides without losing the drift adds +0.5 to the multiplier.',
  'Rente à parede os pontos valem 1,5x, mas encostar zera o combo.': 'Close to the wall points are worth 1.5x, but touching it wipes the combo.',
  'Cada curva recebe uma nota de ângulo, linha e fumaça: SS dá bônus.': 'Every corner is graded on angle, line and smoke: SS gives a bonus.',
  'Na chuva a aderência cai: entre nas curvas mais devagar.': 'Grip drops in the rain: take corners slower.',
  'Na garagem dá para trocar pintura, rodas, aerofólio e a cor do rastro.': 'In the garage you can change paint, wheels, wing and trail color.',
  'No ranking dá para escolher contra qual fantasma correr.': 'In the ranking you can choose which ghost to race.',
  'Tecla F: câmera livre para passear pelo mapa.': 'F key: free camera to explore the map.',
  'Na serra a descida embala o carro: freie antes dos grampos.': 'On the pass the downhill builds speed: brake before the hairpins.',
  'Cada medalha do perfil libera uma pintura, roda, adesivo ou rastro na garagem.': 'Every profile medal unlocks a paint, wheel, sticker or trail in the garage.',
  'Raspar na mureta solta faíscas; bater de verdade zera o combo.': 'Scraping the wall throws sparks; a real hit wipes the combo.',

  // --- Pistas, horários, carros, níveis e motores --------------------------------------------------------------
  'CIRCUITO DO PORTO': 'PORT CIRCUIT',
  'Quarteirões apertados da zona portuária, à noite. Muretas coladas na rua.': 'Tight harbor-district blocks at night. Walls right at the road edge.',
  'NOITE': 'NIGHT',
  'Asfalto úmido, neon e névoa rasteira.': 'Damp asphalt, neon and low mist.',
  'NOITE CHUVOSA': 'RAINY NIGHT',
  'Chuva forte, asfalto espelhado e menos aderência.': 'Heavy rain, mirror-like asphalt and less grip.',
  'ESTRADA DE FUJIMI': 'FUJIMI ROAD',
  'Interior do Japão no fim de tarde: arrozais, vila, grampo no morro e o Monte Fuji ao fundo.': 'Rural Japan at dusk: rice paddies, a village, a hillside hairpin and Mount Fuji behind.',
  'FIM DE TARDE': 'DUSK',
  'Sol baixo, Fuji rosado e arrozais espelhando o céu.': 'Low sun, pink Fuji and paddies mirroring the sky.',
  'Lua sobre o Fuji, lanternas de festival acesas pela vila.': 'Moon over Fuji, festival lanterns lit through the village.',
  'MANHÃ COM NEBLINA': 'MISTY MORNING',
  'Neblina densa no vale; o Fuji aparece acima dela.': 'Thick valley fog; Fuji rises above it.',
  'SERRA DE HAKONE': 'HAKONE PASS',
  'Descida de serra com sete grampos em sequência, muros de pedra e mata fechada; volta subindo pelo vale.': 'A mountain descent with seven back-to-back hairpins, stone walls and dense forest; climbs back up through the valley.',
  'NEBLINA': 'FOG',
  'Céu fechado e neblina subindo do vale: lá embaixo quase não se enxerga.': 'Overcast sky and fog rising from the valley: you can barely see down below.',
  'OUTONO': 'AUTUMN',
  'Fim de tarde com os bordos vermelhos e o lago aparecendo no vale.': 'Late afternoon with red maples and the lake showing in the valley.',
  'Só os postes de sódio dos grampos e a névoa azulada.': 'Only the sodium lamps at the hairpins and a bluish haze.',
  'KAZE 180 TURBO': 'KAZE 180 TURBO',
  'Coupé fastback anos 90 com faróis escamoteáveis, 2.0 turbo de 4 cilindros. Equilibrado e fácil de segurar de lado.': '90s fastback coupé with pop-up headlights and a 2.0 turbo four. Balanced and easy to hold sideways.',
  'SEIRAN S15 SPEC-R': 'SEIRAN S15 SPEC-R',
  'Cupê três volumes do fim dos anos 90, faróis fixos repuxados, com swap de 6 em linha turbo. Entre-eixos curto: gira rápido.': 'Late-90s notchback coupé with swept fixed headlights and a turbo inline-six swap. Short wheelbase: rotates quickly.',
  'CARRO': 'CAR',
  'KAMINARI 86': 'KAMINARI 86',
  'Hatch leve de 1983 com faróis escamoteáveis e pintura de dois tons. Motor 1.6 aspirado de alto giro: pouca força, mas gira rápido e entra de lado com pouco.': 'Light 1983 hatch with pop-up headlights and two-tone paint. High-revving 1.6 naturally aspirated: little power, but it turns in fast and goes sideways easily.',
  '4 CIL. ASPIRADO': 'NA I4',
  'TSUBAME NA ROADSTER': 'TSUBAME NA ROADSTER',
  'Roadster leve de cockpit aberto e faróis escamoteáveis, com swap de motor rotativo. Pouca potência, muito equilíbrio: exige manter o embalo.': 'Light open-top roadster with pop-up headlights and a rotary swap. Little power, lots of balance: you have to keep the momentum.',
  'Esterço todo + acelerador entra de lado; o jogo segura o ângulo e endireita quando você solta.': 'Full lock + throttle kicks it sideways; the game holds the angle and straightens when you let go.',
  'Contra-esterço automático e anti-rodada; o ângulo depende de você dosar acelerador e esterço.': 'Auto counter-steer and anti-spin; the angle depends on how you balance throttle and steering.',
  'Sem assistências. Pede gatilho analógico e contra-esterço na mão.': 'No assists. Needs analog triggers and counter-steering by hand.',
  '4 CIL. TURBO': 'TURBO I4',
  '6 EM LINHA TURBO': 'TURBO INLINE-6',
  'ROTATIVO 2 ROTORES': 'TWIN-ROTOR ROTARY',

  // --- Garagem ----------------------------------------------------------------------------------------------
  'COR ORIGINAL': 'STOCK COLOR', 'VERMELHO SUPER': 'SUPER RED', 'BRANCO PÉROLA': 'PEARL WHITE', 'PRETO NOITE': 'NIGHT BLACK',
  'PRATA LUNAR': 'LUNAR SILVER', 'AZUL MIDNIGHT': 'MIDNIGHT BLUE', 'AMARELO RACING': 'RACING YELLOW', 'VERDE TÓQUIO': 'TOKYO GREEN',
  'LARANJA SUNSET': 'SUNSET ORANGE', 'ROXO NEON': 'NEON PURPLE', 'ROSA SAKURA': 'SAKURA PINK', 'CIANO WANGAN': 'WANGAN CYAN',
  'GRAFITE METÁLICO': 'METALLIC GRAPHITE', 'AZUL BAYSIDE': 'BAYSIDE BLUE', 'VINHO': 'BURGUNDY', 'VERDE LIMA': 'LIME GREEN',
  'ROXO GALÁXIA': 'GALAXY PURPLE', 'OURO CHAMPAGNE': 'CHAMPAGNE GOLD',
  'ORIGINAL': 'STOCK', '6 RAIOS': '6-SPOKE', '5 RAIOS': '5-SPOKE', 'MALHA DAISY': 'DAISY MESH', '8 RAIOS FINOS': 'THIN 8-SPOKE',
  'DISCO FECHADO': 'SOLID DISC', 'RAIOS DUPLOS': 'TWIN-SPOKE',
  'BRONZE': 'BRONZE', 'PRATA': 'SILVER', 'PRETO FOSCO': 'MATTE BLACK', 'DOURADO': 'GOLD', 'BRANCO': 'WHITE', 'GRAFITE': 'GRAPHITE',
  'AZUL': 'BLUE', 'VERMELHA': 'RED', 'OURO ROSÉ': 'ROSE GOLD', 'CROMADA': 'CHROME',
  'SEM AEROFÓLIO': 'NO WING', 'GT ALTO': 'TALL GT', 'DUCKTAIL': 'DUCKTAIL',
  'ALTURA ORIGINAL': 'STOCK HEIGHT', 'REBAIXADO -2 CM': 'LOWERED -2 CM', 'REBAIXADO -4 CM': 'LOWERED -4 CM', 'NO CHÃO -6 CM': 'SLAMMED -6 CM',
  'SEM ADESIVO': 'NO STICKER', 'KAZE (VENTO)': 'KAZE (WIND)', 'ALMA DE DRIFT': 'DRIFT SOUL', 'PATROCÍNIO ZETA': 'ZETA SPONSOR',
  'ALÉM DO LIMITE': 'BEYOND THE LIMIT', 'DEUS DO TOUGE': 'TOUGE GOD',
  'COR DO MULTIPLICADOR': 'MULTIPLIER COLOR', 'CIANO': 'CYAN', 'ROSA NEON': 'NEON PINK', 'ROXO': 'PURPLE', 'VERMELHO': 'RED',
  'ARCO-ÍRIS': 'RAINBOW', 'VERDE NEON': 'NEON GREEN', 'GELO': 'ICE', 'FOGO': 'FIRE',
};
